#! /bin/sh

case "$1" in
   start)
   echo "Load aesd-char-driver"
   /usr/bin/aesdchar_load
   ;;
   stop)
   echo "Unload aesd-char-driver"
   /usr/bin/aesdchar_unload
   ;;
   *)
   echo "Usage: $0 {start|stop}"
   exit 1
   esac
   exit 0
