#! /bin/sh

case "$1" in
   start)
   echo "Starting init script for Module Loading"
   start-stop-daemon -S -n init -a /etc/init.d/scull_load
   start-stop-daemon -S -n init -a /etc/init.d/module_load -- faulty
   modprobe -a hello.ko
   ;;
   stop)
   echo "Removing user modules"
   start-stop-daemon -K -n scull_load
   start-stop-daemon -K -n module_load
   start-stop-daemon -S -n init -a /etc/init.d/scull_unload
   start-stop-daemon -S -n init -a /etc/init.d/module_unload -- faulty
   rmmod hello
   ;;
   *)
   echo "Usage: $0 {start|stop}"
   exit 1
   esac
   exit 0
